apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cabigo-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.cabigo.in
    - admin.cabigo.in
    secretName: cabigo-tls
  rules:
  - host: api.cabigo.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-go-app
            port:
              number: 8081
  - host: admin.cabigo.in
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: admin-dashboard
            port:
              number: 3000
