name: driver_app
description: Minimal driver sample to test OTP flow against backend-go.
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../shared
  http: ^1.2.2
  socket_io_client: ^1.0.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  url_launcher: ^6.2.4
  razorpay_flutter: ^1.3.6
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  google_fonts: ^6.1.0
  sendotp_flutter_sdk: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
