name: customer_app
description: Silver Taxi Customer App - Flutter application for customers
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../shared
  http: ^1.2.2
  socket_io_client: ^1.0.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  url_launcher: ^6.2.4
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  google_maps_flutter: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
