name: customer_app
description: Silver Taxi Customer App - Flutter application for customers
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared:
    path: ../shared
  path_provider: ^2.1.1
  http: ^1.2.2
  socket_io_client: ^1.0.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  url_launcher: ^6.2.4
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  google_maps_flutter: ^2.5.3
  google_places_flutter: ^2.1.1
  sendotp_flutter_sdk: ^0.0.2
  google_fonts: ^6.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/



flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/logo.png" # TODO: Place your icon.png here and run: dart run flutter_launcher_icons
  min_sdk_android: 21
